// js/app.js
const app = document.getElementById('app');
const navLinks = document.querySelectorAll('.nav-link');
const themeToggle = document.getElementById('theme-toggle');

// 테스트 데이터베이스 (각 섹션별 10개씩 총 40개)
const TESTS = [
    // --- 성격 (Personality) ---
    { 
        id: 'real-mbti', category: '성격', title: '나의 진짜 내면 성격 분석', desc: '인간관계와 자아 인식을 바탕으로 분석하는 7단계 심리 분석 보고서.', thumb: 'https://images.unsplash.com/photo-1578632738908-4521c442075a?auto=format&fit=crop&w=500&q=60',
        questions: [{q:'모임에서 당신의 에너지는?',options:[{text:'교류하며 충전',type:'E'},{text:'혼자서 충전',type:'I'}]},{q:'정보를 접할 때?',options:[{text:'가능성에 집중',type:'E'},{text:'사실에 집중',type:'I'}]},{q:'의사결정 시?',options:[{text:'감정과 조화',type:'E'},{text:'논리와 원칙',type:'I'}]},{q:'과제 처리 스타일?',options:[{text:'유연한 대응',type:'E'},{text:'철저한 계획',type:'I'}]},{q:'스트레스 상황에서?',options:[{text:'대화로 푼다',type:'E'},{text:'혼자 정리한다',type:'I'}]},{q:'이상적인 삶?',options:[{text:'도전과 성장',type:'E'},{text:'안정과 평화',type:'I'}]},{q:'주로 듣는 소리는?',options:[{text:'주변의 응원',type:'E'},{text:'내면의 목소리',type:'I'}]}],
        results: { E:{title:'외향적 마스터',desc:'외부 활동에서 힘을 얻는 당신!',img:'https://images.unsplash.com/photo-1559519529-31718974cb14?auto=format&fit=crop&w=500&q=60'}, I:{title:'내향적 성찰가',desc:'내면의 깊이가 남다른 당신!',img:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=500&q=60'} }
    },
    { id:'p2', category:'성격', title:'내면의 색상 테스트', desc:'나의 무의식을 지배하는 컬러는 무엇일까요?', thumb:'https://images.unsplash.com/photo-1502691876148-a84978f59af8?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'열정의 레드',desc:'에너지 넘치는 당신',img:'https://images.unsplash.com/photo-1525909002-1b05e0c869d8?auto=format&fit=crop&w=500&q=60'},B:{title:'평온의 블루',desc:'차분한 당신',img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p3', category:'성격', title:'스트레스 해소 타입', desc:'나에게 가장 잘 맞는 휴식 방법은?', thumb:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'활동형 휴식',desc:'움직여야 풀리는 타입',img:'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=500&q=60'},B:{title:'정적인 휴식',desc:'가만히 있어야 풀리는 타입',img:'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p4', category:'성격', title:'나의 대화 스타일', desc:'주변 사람들이 느끼는 나의 말하기 방식은?', thumb:'https://images.unsplash.com/photo-1521791136364-798a7bc0d262?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'공감형 리스너',desc:'마음을 어루만지는 대화',img:'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=500&q=60'},B:{title:'해결형 조언자',desc:'명쾌한 해답을 주는 대화',img:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p5', category:'성격', title:'연애 가치관 테스트', desc:'내가 추구하는 이상적인 사랑의 모습', thumb:'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'자유로운 연애',desc:'서로의 영역을 존중해요',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=60'},B:{title:'안정적인 연애',desc:'언제나 함께하고 싶어요',img:'https://images.unsplash.com/photo-1516589174184-c685266e4871?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p6', category:'성격', title:'주말 루틴 성향', desc:'토요일 아침, 당신의 선택은?', thumb:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'부지런한 갓생',desc:'계획대로 움직여요',img:'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=500&q=60'},B:{title:'느긋한 힐링',desc:'흐름에 몸을 맡겨요',img:'https://images.unsplash.com/photo-1499914485622-a88fac536bb7?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p7', category:'성격', title:'소비 습관 분석', desc:'돈을 쓸 때 나는 어떤 기분을 느낄까?', thumb:'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'합리적 가치 소비',desc:'꼼꼼하게 따져봐요',img:'https://images.unsplash.com/photo-1554224155-1696413575a8?auto=format&fit=crop&w=500&q=60'},B:{title:'기분파 플렉스',desc:'지금 이 순간이 중요해요',img:'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p8', category:'성격', title:'우정의 깊이', desc:'친구 사이에서 나는 어떤 존재일까?', thumb:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'든든한 버팀목',desc:'깊고 좁은 관계를 선호해요',img:'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=500&q=60'},B:{title:'마당발 분위기메이커',desc:'넓고 다양한 관계가 좋아요',img:'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p9', category:'성격', title:'커리어 성향', desc:'나에게 가장 잘 어울리는 업무 환경은?', thumb:'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'안정적 사무직',desc:'정돈된 환경이 좋아요',img:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=500&q=60'},B:{title:'창의적 프리랜서',desc:'자유로운 변화가 필요해요',img:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=500&q=60'}} },
    { id:'p10', category:'성격', title:'자존감 체크', desc:'내 마음의 단단함 정도 알아보기', thumb:'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'단단한 내면',desc:'자신을 믿는 힘이 강해요',img:'https://images.unsplash.com/photo-1484417894907-623942c8ee29?auto=format&fit=crop&w=500&q=60'},B:{title:'섬세한 감수성',desc:'주변의 영향에 민감해요',img:'https://images.unsplash.com/photo-1494173853739-c21f58b16055?auto=format&fit=crop&w=500&q=60'}} },

    // --- 얼굴 (Face) ---
    { id:'f1', category:'얼굴', title:'프로필 무드 추천', desc:'오늘 나의 얼굴에서 느껴지는 분위기는?', thumb:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'시크한 도시녀',desc:'세련된 무드가 흘러요',img:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=500&q=60'},B:{title:'청순한 요정',desc:'맑고 깨끗한 느낌이에요',img:'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f2', category:'얼굴', title:'비주얼 반응 테스트', desc:'나는 어떤 비주얼에 더 끌릴까?', thumb:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'화려함 선호',desc:'눈에 띄는 매력이 좋아요',img:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=60'},B:{title:'수수함 선호',desc:'자연스러운 매력이 좋아요',img:'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f3', category:'얼굴', title:'첫인상 분석', desc:'처음 만난 사람이 느끼는 나의 온도', thumb:'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'시원한 냉미녀',desc:'도시적이고 지적인 느낌',img:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=60'},B:{title:'따뜻한 온미녀',desc:'다정하고 친근한 느낌',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f4', category:'얼굴', title:'어울리는 메이크업', desc:'나의 장점을 살려줄 메이크업 스타일', thumb:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'내추럴 꾸안꾸',desc:'한 듯 안 한 듯 자연스럽게',img:'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=500&q=60'},B:{title:'화려한 풀메',desc:'포인트가 확실한 스타일',img:'https://images.unsplash.com/photo-1481325545291-94394fe1cf95?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f5', category:'얼굴', title:'퍼스널 컬러 자가 진단', desc:'나에게 생기를 주는 색상은?', thumb:'https://images.unsplash.com/photo-1520691512911-205126938997?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'웜톤',desc:'따뜻한 오렌지, 골드가 잘 어울려요',img:'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=500&q=60'},B:{title:'쿨톤',desc:'차가운 핑크, 실버가 잘 어울려요',img:'https://images.unsplash.com/photo-1542382257-80dedb725088?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f6', category:'얼굴', title:'얼굴형에 맞는 헤어', desc:'나의 리즈를 찾아줄 헤어 스타일', thumb:'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'긴 생머리/웨이브',desc:'여성스러운 매력 발산',img:'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=500&q=60'},B:{title:'트렌디한 단발',desc:'세련되고 발랄한 매력 발산',img:'https://images.unsplash.com/photo-1595476108010-b4d1f8c2b1b1?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f7', category:'얼굴', title:'눈빛의 온도', desc:'내 눈빛은 어떤 이야기를 담고 있을까?', thumb:'https://images.unsplash.com/photo-1546447134-87184a141819?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'강렬한 카리스마',desc:'상대를 압도하는 힘',img:'https://images.unsplash.com/photo-1542513217-0b0eedf7005d?auto=format&fit=crop&w=500&q=60'},B:{title:'촉촉한 감수성',desc:'보호본능을 일으키는 눈빛',img:'https://images.unsplash.com/photo-1516756587022-7891ad56a8cd?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f8', category:'얼굴', title:'미소의 매력', desc:'웃을 때 가장 예뻐 보이는 포인트', thumb:'https://images.unsplash.com/photo-1520155707362-70321722cd66?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'입동굴 미소',desc:'시원시원하고 밝은 에너지',img:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=60'},B:{title:'반달 눈웃음',desc:'보는 사람도 기분 좋아져요',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f9', category:'얼굴', title:'이미지 키워드', desc:'나를 한 단어로 표현한다면?', thumb:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'엘레강스',desc:'우아함이 베어있어요',img:'https://images.unsplash.com/photo-1485875437342-9b39470b3d95?auto=format&fit=crop&w=500&q=60'},B:{title:'큐트',desc:'사랑스러움이 가득해요',img:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=500&q=60'}} },
    { id:'f10', category:'얼굴', title:'비주얼 분위기', desc:'나만의 독보적인 분위기 찾기', thumb:'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'유니크한 개성',desc:'누구와도 대체할 수 없는 나',img:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=500&q=60'},B:{title:'클래식한 정석',desc:'유행을 타지 않는 아름다움',img:'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=500&q=60'}} },

    // --- 사주 (Fortune) ---
    { id:'t1', category:'사주', title:'오늘의 운세', desc:'오늘 당신에게 찾아올 행운은?', thumb:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'최고의 행운',desc:'모든 일이 술술 풀려요',img:'https://images.unsplash.com/photo-1519068737630-e5db30e12e42?auto=format&fit=crop&w=500&q=60'},B:{title:'평온한 하루',desc:'작은 기쁨이 있는 날',img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t2', category:'사주', title:'재물운 분석', desc:'금전적 흐름이 좋아지는 시기', thumb:'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'재물복 충만',desc:'기대하지 않은 수익이 생길지도!',img:'https://images.unsplash.com/photo-1559526324-4b87b5e36e40?auto=format&fit=crop&w=500&q=60'},B:{title:'절약이 필요한 때',desc:'지출 관리에 신경 써보세요',img:'https://images.unsplash.com/photo-1579621970795-87facc2f976d?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t3', category:'사주', title:'연애운 자가 진단', desc:'언제쯤 좋은 인연을 만날까?', thumb:'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'연애의 봄날',desc:'곧 설레는 만남이 찾아와요',img:'https://images.unsplash.com/photo-1518107616385-ad30833edce7?auto=format&fit=crop&w=500&q=60'},B:{title:'자기 계발의 시기',desc:'자신을 먼저 사랑해주세요',img:'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t4', category:'사주', title:'취업/성공운', desc:'나의 커리어는 어디로 흐르고 있을까?', thumb:'https://images.unsplash.com/photo-1454165833767-027ffea7025c?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'승승장구',desc:'원하는 목표를 달성할 거예요',img:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=500&q=60'},B:{title:'인내가 필요한 도약기',desc:'준비 기간이 빛을 발할 거예요',img:'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t5', category:'사주', title:'건강운 체크', desc:'나의 에너지를 채우는 방법', thumb:'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'활기찬 에너지',desc:'몸도 마음도 가뿐해요',img:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=500&q=60'},B:{title:'충전이 필요해',desc:'충분한 휴식을 취해보세요',img:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t6', category:'사주', title:'인복 테스트', desc:'나의 주변에는 어떤 사람들이 모일까?', thumb:'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'귀인 운이 가득',desc:'도와주는 사람이 많은 인생',img:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=500&q=60'},B:{title:'독립적인 선구자',desc:'스스로 길을 개척하는 스타일',img:'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t7', category:'사주', title:'올해의 행운 키워드', desc:'2026년 나를 빛나게 할 단어', thumb:'https://images.unsplash.com/photo-1533234407053-ada8c9579737?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'성장과 변화',desc:'새로운 분야에 도전하세요',img:'https://images.unsplash.com/photo-1444464666168-49d633b867ad?auto=format&fit=crop&w=500&q=60'},B:{title:'안정과 결실',desc:'노력한 결과를 얻게 됩니다',img:'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t8', category:'사주', title:'이달의 조언', desc:'이번 달 조심해야 할 것과 챙겨야 할 것', thumb:'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'과감한 실행',desc:'망설이지 말고 나아가세요',img:'https://images.unsplash.com/photo-1532619675605-1fea662ec0b9?auto=format&fit=crop&w=500&q=60'},B:{title:'신중한 판단',desc:'한 번 더 생각하고 결정하세요',img:'https://images.unsplash.com/photo-1454165833767-027ffea7025c?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t9', category:'사주', title:'사주로 보는 성격', desc:'태어난 기운으로 알아보는 나', thumb:'https://images.unsplash.com/photo-1515023115689-589c33041d3c?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'나무의 기운',desc:'곧고 성실한 성품',img:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=500&q=60'},B:{title:'물의 기운',desc:'유연하고 지혜로운 성품',img:'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=500&q=60'}} },
    { id:'t10', category:'사주', title:'운명의 짝꿍 궁합', desc:'나와 잘 맞는 사람의 특징', thumb:'https://images.unsplash.com/photo-1516589174184-c685266e4871?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'보완해주는 관계',desc:'서로의 부족함을 채워줘요',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=60'},B:{title:'닮은꼴 관계',desc:'말하지 않아도 잘 통해요',img:'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=500&q=60'}} },

    // --- 재미 (Fun) ---
    { id:'u1', category:'재미', title:'인생 밸런스 게임', desc:'당신의 선택은? 고르기 힘든 난제들', thumb:'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'확고한 주관',desc:'자신의 선택에 후회가 없어요',img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=60'},B:{title:'유연한 사고',desc:'상황에 따라 다를 수 있죠',img:'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u2', category:'재미', title:'나의 전생 알아보기', desc:'과거의 나는 어떤 모습이었을까?', thumb:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'자유로운 방랑자',desc:'세상을 유람하던 영혼',img:'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=500&q=60'},B:{title:'지혜로운 학자',desc:'진리를 탐구하던 영혼',img:'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u3', category:'재미', title:'소울푸드 찾기', desc:'지친 나를 위로해줄 단 하나의 음식', thumb:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'매콤한 떡볶이',desc:'스트레스를 한 번에 날려요',img:'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=500&q=60'},B:{title:'달콤한 디저트',desc:'당 충전으로 기분 전환',img:'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u4', category:'재미', title:'당장 떠나고 싶은 여행지', desc:'나의 무의식이 원하는 휴식처', thumb:'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'에메랄드빛 바다',desc:'파도 소리와 함께하는 힐링',img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=60'},B:{title:'화려한 대도시',desc:'쇼핑과 맛집이 가득한 곳',img:'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u5', category:'재미', title:'나만의 힐링 스타일', desc:'지친 하루 끝, 나를 안아주는 법', thumb:'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'반신욕과 명상',desc:'몸의 긴장을 풀어줘요',img:'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=500&q=60'},B:{title:'좋아하는 영화 정주행',desc:'다른 세상으로의 탈출',img:'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u6', category:'재미', title:'인생 영화 취향', desc:'내가 영화 속 주인공이라면?', thumb:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'로맨틱 코미디',desc:'사랑스럽고 즐거운 인생',img:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=500&q=60'},B:{title:'미스터리 스릴러',desc:'긴장감 넘치는 인생',img:'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u7', category:'재미', title:'음악 취향 테스트', desc:'나의 플레이리스트가 말해주는 성격', thumb:'https://images.unsplash.com/photo-1514525253361-bee871870472?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'서정적인 발라드',desc:'풍부한 감수성의 소유자',img:'https://images.unsplash.com/photo-1459749411177-042180ce673c?auto=format&fit=crop&w=500&q=60'},B:{title:'에너지틱한 댄스곡',desc:'밝고 활동적인 에너지',img:'https://images.unsplash.com/photo-1514525253361-bee871870472?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u8', category:'재미', title:'나와 어울리는 반려동물', desc:'나의 성향과 찰떡궁합인 동물은?', thumb:'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'충직한 강아지',desc:'함께 교감하는 걸 좋아해요',img:'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=500&q=60'},B:{title:'도도한 고양이',desc:'적당한 거리를 소중히 해요',img:'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u9', category:'재미', title:'가장 좋아하는 계절', desc:'계절이 바뀌면 생기는 변화들', thumb:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'화사한 봄/여름',desc:'열정과 생동감이 넘쳐요',img:'https://images.unsplash.com/photo-1462270662277-5156c1d73894?auto=format&fit=crop&w=500&q=60'},B:{title:'차분한 가을/겨울',desc:'깊은 사색과 분위기를 즐겨요',img:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=500&q=60'}} },
    { id:'u10', category:'재미', title:'행운의 아이템 찾기', desc:'오늘 나에게 행운을 가져다줄 물건', thumb:'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=500&q=60', questions:[{q:'1',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'2',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'3',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'4',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'5',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'6',options:[{text:'A',type:'A'},{text:'B',type:'B'}]},{q:'7',options:[{text:'A',type:'A'},{text:'B',type:'B'}]}], results:{A:{title:'반짝이는 액세서리',desc:'자신감을 높여줘요',img:'https://images.unsplash.com/photo-1515562141207-7a18b5ce33c7?auto=format&fit=crop&w=500&q=60'},B:{title:'포근한 스카프/향수',desc:'편안한 기분을 만들어줘요',img:'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=500&q=60'}} }
];

let currentFilter = '전체';

// 라우터 강화 (새로운 카테고리 지원)
function router() {
    const hash = window.location.hash || '#home';
    navLinks.forEach(link => {
        const filter = link.dataset.filter;
        link.classList.toggle('active', (hash === '#home' && filter === '전체') || hash.includes(filter?.toLowerCase()));
    });

    if (hash === '#privacy') renderPrivacy();
    else if (hash === '#about') renderAbout();
    else if (hash === '#terms') renderTerms();
    else if (hash === '#contact') renderContact();
    else if (hash.startsWith('#test/')) renderTestExecution(hash.split('/')[1]);
    else {
        const filterMap = { '#personality': '성격', '#face': '얼굴', '#fortune': '사주', '#fun': '재미' };
        currentFilter = filterMap[hash] || '전체';
        renderHome();
    }
    window.scrollTo(0, 0);
}

function renderHome() {
    const filtered = currentFilter === '전체' ? TESTS : TESTS.filter(t => t.category === currentFilter);
    app.innerHTML = `
        <div class="ad-slot">SevenCheck : 2030 여성을 위한 감성 분석 서비스</div>
        <section class="portal-hero">
            <h1>SevenCheck : 7번으로 만나는 진실</h1>
            <p>나의 성격, 비주얼 분위기, 운세까지.<br>당신을 더 깊이 이해하는 시간을 가져보세요.</p>
        </section>

        <div class="test-grid">
            ${filtered.map(t => `
                <a href="#test/${t.id}" class="test-card fade-in">
                    <div class="test-thumb" style="background-image: url('${t.thumb}')"></div>
                    <div class="test-info">
                        <span class="test-category-tag">${t.category}</span>
                        <h3>${t.title}</h3>
                        <p>${t.desc}</p>
                    </div>
                </a>
            `).join('')}
        </div>
    `;
}

function renderPrivacy() {
    app.innerHTML = `
        <div class="card legal-page">
            <h2>개인정보처리방침</h2>
            <p>SevenCheck Studio(이하 '회사')는 이용자의 개인정보를 중요시하며, 관련 법규를 준수합니다.</p>
            <h3>1. 수집 항목</h3>
            <p>사용자가 선택한 테스트 결과값은 서버에 저장되지 않고 일회성으로 소비됩니다.</p>
        </div>
    `;
}

function renderAbout() {
    app.innerHTML = `
        <div class="card legal-page">
            <h2>서비스 소개</h2>
            <p>SevenCheck는 '7번의 질문'을 통해 스스로를 돌아볼 기회를 제공합니다.</p>
        </div>
    `;
}

function renderTerms() { app.innerHTML = `<div class="card legal-page"><h2>이용약관</h2><p>본 서비스의 모든 콘텐츠는 SevenCheck Studio에 저작권이 있습니다.</p></div>`; }
function renderContact() { app.innerHTML = `<div class="card legal-page"><h2>문의하기</h2><p>Email: support@sevencheck.studio</p></div>`; }

function renderTestExecution(testId) {
    const test = TESTS.find(t => t.id === testId);
    if (!test) return location.hash = '#home';
    let step = 0; const answers = [];
    const updateStep = () => {
        const currentQ = test.questions[step];
        app.innerHTML = `
            <div class="test-execution fade-in">
                <div class="progress-container"><div class="step-dots">${Array.from({length: 7}).map((_, i) => `<div class="dot ${i <= step ? 'active' : ''}"></div>`).join('')}</div></div>
                <h2 style="font-size:1.5rem; margin-bottom:2rem;">Q${step + 1}. ${currentQ.q}</h2>
                <div class="options">${currentQ.options.map(opt => `<button class="option-btn" data-type="${opt.type}">${opt.text}</button>`).join('')}</div>
            </div>
        `;
        document.querySelectorAll('.option-btn').forEach(btn => {
            btn.onclick = () => {
                answers.push(btn.dataset.type);
                if (step < 6) { step++; updateStep(); } 
                else { renderResult(testId, answers); }
            };
        });
    };
    updateStep();
}

function renderResult(testId, answers) {
    const test = TESTS.find(t => t.id === testId);
    const counts = answers.reduce((acc, type) => { acc[type] = (acc[type] || 0) + 1; return acc; }, {});
    const winningType = Object.keys(counts).sort((a, b) => counts[b] - counts[a])[0];
    const result = test.results[winningType];

    app.innerHTML = `
        <div class="result-card fade-in">
            <span class="test-category">${test.title} 결과 분석</span>
            <div class="result-img" style="background-image: url('${result.img}'); background-size: cover;"></div>
            <h2 style="font-size:2rem; color:var(--accent-color); margin-bottom:1rem;">당신은 [${result.title}]</h2>
            <div class="result-long-desc" style="text-align:left; line-height:1.8; margin-bottom:2rem;">
                <p>${result.desc}</p>
            </div>
            <div class="share-grid">
                <button class="btn-share" id="share-web">SNS 공유</button>
                <button class="btn-share btn-copy" id="share-copy">링크 복사</button>
            </div>
            <button class="btn-share" style="width:100%; margin-top:1rem; background:var(--text-main);" onclick="location.hash='#home'">다른 분석 더 보기</button>
        </div>
    `;

    document.getElementById('share-copy').onclick = () => {
        navigator.clipboard.writeText(window.location.href); alert('링크가 복사되었습니다!');
    };
    document.getElementById('share-web').onclick = async () => {
        if (navigator.share) {
            try { await navigator.share({ title: 'SevenCheck', text: `나의 결과: ${result.title}`, url: window.location.href }); } catch (err) {}
        }
    };
}

themeToggle.onclick = () => {
    const next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    themeToggle.textContent = next === 'dark' ? '☀️' : '✨';
};

window.addEventListener('hashchange', router);
window.addEventListener('load', router);
router(); // Initial call
